### ISSUE TITLE
Palette close buttons don't work

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#11]
The close buttons on the Tray*, Markers, and Messages palettes don't work.  If I click them, the palette closes for an instant, and then reappears.

**Comment by wsu-cb** [comment]
Clarification:  I mean the X buttons on the top right of the palettes, not the toolbar buttons.

Also, the CBDesign Tile and Color palettes have the same problem.

**Comment by DLLarson** [comment]
Fix works great!

-Dale
