### ISSUE TITLE
CTileManager::FindNamedTileSet() reversed sense?

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#110]
https://learn.microsoft.com/en-us/cpp/atl-mfc-shared/reference/cstringt-class?view=msvc-170#comparenocase says that the strings are equal when the `CompareNoCase()` return value is `0`.  Given that, it looks like `CTileManager::FindNamedTileSet()` is using `CompareNoCase()` backwards.  I have confirmed that tag `v3.5-prerelease-2` uses the same logic as the current version, but it still looks wrong to me.  Dale, can you confirm that `CTileManager::FindNamedTileSet()` is currently buggy?

**Comment by DLLarson** [comment]
>Given that, it looks like CTileManager::FindNamedTileSet() is using CompareNoCase() backwards. ... 
>Dale, can you confirm that CTileManager::FindNamedTileSet() is currently buggy?

It's definitely a bug... which begs the question: Why didn't we see it until now? 

The only code that calls it is `CGeomorphicBoard::GetSpecialTileSet()` and the `FindNamedTileSet` logic will--with high certainty--always return non-zero so some other TileSet (probably the first in the list) will be returned instead. This will cause graphics to be added to the wrong TileSet. I'm not sure what broader implications that will have.

-Dale

**Comment by wsu-cb** [comment]
> The only code that calls it is `CGeomorphicBoard::GetSpecialTileSet()` and the `FindNamedTileSet` logic will--with high certainty--always return non-zero so some other TileSet (probably the first in the list) will be returned instead. This will cause graphics to be added to the wrong TileSet. I'm not sure what broader implications that will have.
> 
> -Dale

That was my conclusion as well.  I suspect that it didn't hurt much since the same (for any specific `.gam`/`.gbx`) `TileSet` will always be returned because the function is only used by `CBPlay`, which won't ever create or destroy a `TileSet`.  Nevertheless, I will fix this.
