### ISSUE TITLE
add wxWidgets

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#118]
Dale,
The next major step for #116 is to add wxWidgets to CB.

1) I am thinking of doing so by making wxWidgets a git submodule of CB.  Do you object to making our git setup somewhat more complicated?
2) I will also have to investigate how to drive the build process.  The simple solution is just to have the builder run the wxWidgets build as one step, and then the CB as a second step.  However, I know that wxWidgets includes support for building via CMake, and I have co-workers who use CMake from within Visual Studio.  I have no experience with this, but from listening to my co-workers, it sounds like we could re-design the CB build to be drive by CMake, even when run from Visual Studio.  If we did this, it would be a good step on the way to cross-platform builds.  How would you feel about this approach?

Note that these are topics for investigation, not actual plans; I might discover that either or both of these ideas doesn't work out well, and be forced to try other approaches.

**Comment by DLLarson** [comment]
Closing since CMake and wxWidgets have reached `master`.
