### ISSUE TITLE
help compiler exit value

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#120]
As part of adding wxWidgets as a library for CB, I am trying to create CMake files to build CB and wxWidgets.  However, I am running into trouble converting the .chm file generation into CMake commands.  Is there documentation for `hhc.exe` somewhere?  In particular, is the process exit value actually **1 for success** and **0 for failure**, contrary to standard practice?  Experimenting with `hhc` seems to show this, but it's so non-standard that I'm having a hard time believing the results of my experiments.

**Comment by DLLarson** [comment]
Hi Bill,

First I apologize for losing track of this issue that you entered. I just stumbled over the Email for it today. My bad.

Here's a link to some information on installing tools and documentation for HTML help:

https://learn.microsoft.com/en-us/answers/questions/922894/how-do-i-install-microsoft-html-help-workshop

Here are the tools and documentation that I could find. I bundled it all into a single ZIP file:

[WinHTMLHelpToolsAndDocs.zip](https://github.com/CyberBoardPBEM/cbwindows/files/11930104/WinHTMLHelpToolsAndDocs.zip)

I didn't find specific documentation for `hhc.exe` but it might be in the above package.

-Dale

**Comment by DLLarson** [comment]
>is the process exit value actually 1 for success and 0 for failure, contrary to standard practice? Experimenting with hhc seems to show this, but it's so non-standard that I'm having a hard time believing the results of my experiments.

My testing shows the same. The exact opposite of convention:

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files\Microsoft Visual Studio\2022\Community>hhc

Usage:   hhc <filename>
    where <filename> = an HTML Help project file
Example: hhc myfile.hhp

C:\Program Files\Microsoft Visual Studio\2022\Community>echo %errorlevel%
24

C:\Program Files\Microsoft Visual Studio\2022\Community>hhc foobar
Unable to open foobar.
C:\Program Files\Microsoft Visual Studio\2022\Community>echo %errorlevel%
0

C:\Program Files\Microsoft Visual Studio\2022\Community>
```
-Dale

**Comment by wsu-cb** [comment]
> > is the process exit value actually 1 for success and 0 for failure, contrary to standard practice? Experimenting with hhc seems to show this, but it's so non-standard that I'm having a hard time believing the results of my experiments.
> 
> My testing shows the same. It's the exact opposite of convention:
> 

I found only a tiny reference to `hhc.exe` in the `.zip`, but since we're seeing the same behavior, strange as it is, I will write the build files accordingly.
