### ISSUE TITLE
Is CPalette sufficiently obsolete to remove?

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#128]
The `CPalette` code is largely obsolete, and not very portable. 
1) https://github.com/CyberBoardPBEM/cbwindows/issues/122#issuecomment-1704392699
2) https://docs.wxwidgets.org/latest/classwx_palette.html
3) According to `GetDeviceCaps(dc, RASTERCAPS)` and `GetSystemPaletteEntries()`, my laptop's graphics don't even have palette support.  (At least, assuming I have used those functions correctly.  Even when I was doing Win32 MFC development full-time professionally, I'm reasonably sure I never used a palette.)

Is it acceptable to remove the palette code?  It would reduce the effort to convert to wxWidgets.

**Comment by DLLarson** [comment]
>Is it acceptable to remove the palette code? It would reduce the effort to convert to wxWidgets.

Yes. I doubt there are any palette based graphics cards in existence except in a museum.

We just need to ensure we can always upgrade the earlier palette based CB files.

-Dale

**Comment by wsu-cb** [comment]
> We just need to ensure we can always upgrade the earlier palette based CB files.

Agreed, but I believe all of that code is encapsulated in the `CDib` class, and doesn't use `CPalette`.  I'm specifically talking about eliminating use of `CPalette` and the associated WM_* messages (which I only now have noticed are only handled in CBDesign, not CBPlay).

**Comment by DLLarson** [comment]
>Agreed, but I believe all of that code is encapsulated in the CDib class, and doesn't use CPalette.

That works for me.
