### ISSUE TITLE
Should printing be supported or forbidden?

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#131]
I have discovered that printing appears to be in a half-baked state.  I had assumed it wasn't implemented at all, but there are actually a few vestiges of it in the system, and using `Ctrl+P` in `CBrdEditView` in CBDesign will actually start printing.  However, it is unsafe:  Printing a tile seems to always trigger an assert and generally not succeed, and the `.gbx` in 
[print-crash.zip](https://github.com/user-attachments/files/16041653/print-crash.zip) will actually cause CBDesign to crash.  Note that this is not a new issue; CBDesign 3.10 crashes when printing the board in this `.gbx`.

In the short term, I think we should simply prevent any attempt to print rather than trying to fix printing.

We could treat the failure of print as a bug, but my opinion is we should just forbid printing, or at most consider it a very low priority enhancement request.

**Comment by DLLarson** [comment]
Hi Bill,

>In the short term, I think we should simply prevent any attempt to print rather than trying to fix printing.

I never implemented printing support. MFC does provide a sorta lame implementation for it. I didn't know any of the UI elements could still trigger it.

>but my opinion is we should just forbid printing

Agreed.

-Dale

**Comment by wsu-cb** [comment]
> I never implemented printing support. MFC does provide a sorta lame implementation for it. I didn't know any of the UI elements could still trigger it.
> 
> > but my opinion is we should just forbid printing
> 
> Agreed.

OK.  I will include that in my next PR.
