### ISSUE TITLE
right-side palettes keep becoming very wide

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#16]
In CBPlay, the piece and marker palettes on the right side of the screen keep taking up most of the screen width.  I adjust the width back down, save the game, close the game, and then open the game, and the palettes are back to being really wide.

**Comment by wsu-cb** [comment]
I think I have figured out how to reproduce this:
1)  Open a .gam
2)  Open all the right side palettes (TrayA/TrayB/Markers)
3)  Use the mouse to make the right side palettes "very wide"
4)  Close TrayA and TrayB
5)  Use the mouse to make the right side palettes (i.e., just Markers currently) "normal width"
6)  Save .gam
7)  Close .gam
8)  Open (the same) .gam

The result will be the right side palettes (i.e., just Markers currently) are "very wide"

**Comment by wsu-cb** [comment]
It looks like MFC remembers the width of the individual palettes even after they have been closed, and doesn't adjust the size of the hidden palettes when the container window is given a smaller size.  When the .gam is re-opened, the container window adjusts to fit the maximum child width even though the large children are not shown.  It seems like the best thing to do is notify the hidden children when the container window's size change, but it's not clear why MFC doesn't do that automatically, nor how to do it ourselves.

**Comment by wsu-cb** [comment]
I have now realized that there is a simpler way to observe this problem:

1)  Open a .gam
2)  Open all the right side palettes (TrayA/TrayB/Markers)
3)  Use the mouse to make the right side palettes "very wide"
4)  Close TrayB
5)  Use the mouse to make the right side palettes "normal width"
6)  Open TrayB

The result will be the right side palettes are "very wide"

**Comment by DLLarson** [comment]
Superb analysis of the issue!

I've verified that your fix works.

I did have one weird problem. I saved the file with the updated layout and the two bottom tray/marker palettes are squashed to the bottom. No matter how I resize them this still happens.

I'll keep the PR unmerged in case this is related to the fix.

Thanks!

----
A suggestion for future pull request work...

The safest (and designed) way to work on changes for the upstream repo  on GitHub is to fork the repo to your personal area. Create branches and pull request from there.

Since you're a member of the Organization you are allowed to create branches on the main repo but it's not a good practice. Anybody outside the organization cannot do this and must create a fork and submit pull requests from there.

-Dale

**Comment by wsu-cb** [comment]
> I did have one weird problem. I saved the file with the updated layout and the two bottom tray/marker palettes are squashed to the bottom. No matter how I resize them this still happens.
> 
> I'll keep the PR unmerged in case this is related to the fix.

This probably is a bug in my work.  I saw that happen when I was working on this bug, but I thought I had fixed it.  However, if you are still seeing it, I probably missed something.  Do you have any hints on how to reproduce this?

**Comment by wsu-cb** [comment]
> A suggestion for future pull request work...
> 
> The safest (and designed) way to work on changes for the upstream repo on GitHub is to fork the repo to your personal area. Create branches and pull request from there.
> 
> Since you're a member of the Organization you are allowed to create branches on the main repo but it's not a good practice. Anybody outside the organization cannot do this and must create a fork and submit pull requests from there.
> 
> -Dale

Since it looks like the current attempt did not succeed, do you want to reject this pull request, and have me do a fork and start over?

**Comment by DLLarson** [comment]
>Since it looks like the current attempt did not succeed, do you want to reject this pull request, and have me do a fork and start over?

No to "reject the PR".

Doing the fork is a good idea. When you fork you'll also get a copy of your working branch in the upstream repo.

You can proceed various ways. What I usually do is make the fix on my working branch and then force push the new commit over the previous set with `git push -f` command. 

GitHub will recognize an updated PR and do the usual sanity checks. That code can then be reinspected under the same issue and PR. This keeps the amount of PR's and extraneous "sausage making" commits to a minimum.

Also, I try to keep the history clean of merge commits by insisting on rebased commits when adding the upstream 'master'.

-Dale

**Comment by DLLarson** [comment]
>Do you have any hints on how to reproduce this?

I'm using the attached files for Paths of Glory. 

[POG-TestFiles.zip](https://github.com/CyberBoardPBEM/cbwindows/files/5251967/POG-TestFiles.zip)

I just set the size of the trays, save, close and reload. I then see squashed bottom palettes.

-Dale

**Comment by wsu-cb** [comment]
> > Since it looks like the current attempt did not succeed, do you want to reject this pull request, and have me do a fork and start over?
> 
> No to "reject the PR".
> 
> Doing the fork is a good idea. When you fork you'll also get a copy of your working branch in the upstream repo.
> 
> You can proceed various ways. What I usually do is make the fix on my working branch and then force push the new commit over the previous set with `git push -f` command.
> 
> GitHub will recognize an updated PR and do the usual sanity checks. That code can then be reinspected under the same issue and PR. This keeps the amount of PR's and extraneous "sausage making" commits to a minimum.
> 
> Also, I try to keep the history clean of merge commits by insisting on rebased commits when adding the upstream 'master'.
> 
> -Dale

If I do a fork without a new PR, how can GitHub recognize that a push in the fork is related to this PR?

**Comment by DLLarson** [comment]
It should recognize the overwritten former commit. I've never had an issue with this. I always use the same topic branch so perhaps that's key to the scheme but it does work.

The workflow is similar to how Gerrit handles the sausage making of their rendition of pull requests.

-Dale

**Comment by wsu-cb** [comment]
I forked cbwindows to https://github.com/wsu-cb/cbwindows.  In the fork, I have rebased this branch to the current master, and I think I have fixed the squashed palette problem.  I have pushed the fix to https://github.com/wsu-cb/cbwindows/tree/fix-wide-palettes.  It doesn't look like my fix is being detected by GitHub as part of the existing pull request, but it has occurred to me to make a new PR from https://github.com/wsu-cb/cbwindows/tree/fix-wide-palettes to https://github.com/CyberBoardPBEM/cbwindows/tree/fix-wide-palettes.  Once the changes in the fork are pulled into the main repo's branch, maybe then the old PR will update.  Should I generate the fork_branch-to-main_branch PR and see if that actually works?

**Comment by DLLarson** [comment]
This is getting complicated....

Let's try this, if it doesn't work we'll just drop the old PR and move on.

1) Clone the upstream repository to a new place on your system (i.e.,
forget about the fork for this Issue/PR.).
2) Check out your "fix-wide-palettes" branch.
3) Rebase the branch against the master.
4) Then force push via "git push -f origin fix-wide-palettes". This should
cause the new push to replace the PR's previous commit. GitHub should also
trigger a build as a sanity check for the new commit.
5a) If step (4) works then you should be able to make additional changes
and force push those the same way for code review.
5b) If step (4) didn't work just drop the old PR and reissue a new PR from
your forked repository.

-Dale
