### ISSUE TITLE
width of right side palettes is not restored by CWinStateManager

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#20]
Is the following a bug or a feature?

1)  Open a .gam
2)  Make the right side dock "very wide"
3)  Save the .gam
4)  Make the right side dock "normal width"
5)  Close the .gam
6)  Open the .gam
-->
The right side dock is "normal width".  The CWinStateManager has not restored the palette layout as it was when the .gam was saved.

Note:  If this is a feature, then there is a bug in the feature:  If a CPlayBoardView is the topmost child frame when the .gam is saved, its width at the time of the save is restored when the .gam is opened.  This results in a weird display because the board is narrow, and the right dock is narrow, leaving a gap between them where the project view shows through.  This can be fixed by adding
`(DYNAMIC_DOWNCAST(CMDIFrameWndEx, AfxGetMainWnd()))->RecalcLayout();`
to the end of CWinStateManager::RestoreStateOfDocumentFrames().

**Comment by DLLarson** [comment]
(Rusty brain cells engaged...)

The original idea was to save the layout of the game and restore it upon opening the game. It seems that the new additions of MFC must want to set the layout to be the last used by the application. These two schemes appear to be in conflict. 

I prefer the game restoring its layout if it's still possible without the MFC stuff getting in the way.

The gapping of windows definitely sounds like a bug.

-Dale

**Comment by wsu-cb** [comment]
Could you clarify what specifically you mean by "game restoring its layout"?  CWinStateManager::RestoreStateOfDocumentFrames() has a comment that appears to say that it restores frames, but not palettes.  That's the crux of the question:  Was that by design, or was that a bug that you hadn't had time to fix?  If all windows are restored, there would be no gapping of windows.

For what it's worth, when I run this experiment on CB 3.10, it seems to use the palette width set after the save, and adjusts the frames to match.

**Comment by DLLarson** [comment]
>For what it's worth, when I run this experiment on CB 3.10, it seems to use the palette 
>width set after the save, and adjusts the frames to match.

That's worth a lot. 

For me that's the golden behavior because it's what people are familiar with. Breaking familiar patterns should have a good reason to do so.

My detailed memory of such things can be flawed. The shipping program's behaviors are the final arbiter of truth. The question is will the new MFC stuff that replaced CodeJock's allow for the same behavior.

-Dale
