### ISSUE TITLE
CTileSheet::ClearSheet() deletes non-heap m_pDC

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#37]
CTileSheet::ClearSheet() calls `delete m_pDC`.  However, my reading of the code says `m_pDC` never contains a heap-allocated object.  Fortunately, my reading of the `CTileSheet` code is that `CTileSheet::ClearSheet()` is never called with `m_pDC != NULL`.

Nevertheless, I think the code should be rewritten to reflect the current behavior.

(Actually, the way I read the code, I think m_pDC should be removed from the class entirely.  It looks to me like it's only used as a transient value, and should only be stored on the stack.)

**Comment by DLLarson** [comment]
You are correct.

This looks like a remnant of a move to some global DC's a long time ago. I'm sure I did it for Win16 performance (speed AND memory) reasons. You can see that the value is populated by `CTileSheet::CreateSheetDC()` and de-populated by `CTileSheet::DeleteSheetDC()` which at some point created/destroyed the needed BLTter DC on the fly. So I hooked the "fix" in at this level. The cleanup code you pointed out is left over from those days.

-Dale
