### ISSUE TITLE
possible extraneous member variable CMarkListBox::m_bDisplayIDs

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#41]
If I change `CMarkListBox::m_bDisplayIDs` to type `const int`, the compiler reports no errors for attempting to assign to it.  Therefore, I think it is currently unused.

Since `CMarkListBox` is derived from `CTileBaseListBox`, and there is also declared `CTileBaseListBox::m_bDisplayIDs`, which is in use, I suspect that `CMarkListBox::m_bDisplayIDs` should be removed.

Does this appear correct?

**Comment by DLLarson** [comment]
>Therefore, I think it is currently unused.

Actually it is used. This flag is set by the `CTileListBox` constructor by reading the registry:

```
    m_bDisplayIDs = AfxGetApp()->GetProfileInt("Settings", "DisplayIDs", 0);
```

It's used for diagnosis of various ID's (Tiles, etc...) by showing the ID's in the UI to compare against other ID dump tools hidden in the code.

I think the reason it didn't trip a compiler error is because it was set in the constructor of the containing class.

-Dale

**Comment by wsu-cb** [comment]
Doesn't `CTileListBox`'s constructor set `CTileListBox::m_bDisplayIDs`?  As a derived class, I don't think `CTileListBox`'s constructor can reach `CMarkListBox::m_bDisplayIDs`.

If `CMarkListBox::m_bDisplayIDs` is used for a different purpose than `CTileListBox::m_bDisplayIDs`, why does it have the same name?

On the other hand, if it is used for the same purpose, why can't it just use `CTileListBox::m_bDisplayIDs` (since the base class version is protected, and thus accessible to the derived class)?

**Comment by DLLarson** [comment]
>On the other hand, if it is used for the same purpose, why can't it just 
>use CTileListBox::m_bDisplayIDs (since the base class version is protected, and 
>thus accessible to the derived class)?

My bad. 

I missed the specificity of the `CMarkListBox` class. That `CMarkListBox::m_bDisplayIDs` member appears to be a copy/paste code cloning remnant. It's dead code as you indicate.

Also, my explanation in an earlier post...

>It's used for diagnosis of various ID's (Tiles, etc...) 

...needs to be refined. It shows the Tile ID's only for various elements in the GUI. I used it to run down some tile reference issue a long time ago along with a hidden hotkey to dump the TileID's related internal tables. I generally like to leave simple tools like this in "just-in-case".

Sorry for the diversion.

-Dale
