### ISSUE TITLE
CGbxProjView::DoBoardClone() may fail

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#44]
Important:  Start with GM not running

1)  Open GM
2)  Create a new .gbx
3)  Create a new board
4)  Clone the new board

--> The cloned board is not created.

The problem is that CGamDoc::SetLoadingVersion() isn't called until a .gbx is loaded.  If no .gx is loaded before cloning a board, the Serialize code used by the clone process doesn't know the correct file version.

**Comment by DLLarson** [comment]
Nice catch!
-Dale
