### ISSUE TITLE
problem when changing CTrayPalette tray name with keyboard

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#48]
1)  Open a .gam with multiple piece trays
2)  Open a tray palette
3)  Using the mouse, drop down the tray palette's list of names
4)  Using the keyboard arrow keys, change the selected name, and hit Enter

--> The drop down closes, the tray palette name shows the selected name, but the displayed pieces are from the old piece tray

I see that `CTrayPalette::OnTrayNameCbnSelchange()` explicitly does not update the tray list when the drop down is open, but that causes this problem.  (If I remove the blocking `if` test, the correct pieces are displayed.)

With the `if` test disabled, I see that updating the tray piece display causes changing the selected name with the keyboard arrows to be very slightly sluggish, so not updating the piece display may be intentional.  If that is the case, then I think we need to add handling for `ON_CBN_SELENDOK` to update the piece display. However, my preference is to make the piece display correspond to the focused name despite the slight delay.  (This may be a case of modern computers' better performance making some UI sacrifices unnecessary.)

Is making the piece display static while using the keyboard arrows intentional?

**Comment by DLLarson** [comment]
>Is making the piece display static while using the keyboard arrows intentional?

No. It's definitely a bug.

-Dale

**Comment by wsu-cb** [comment]
> > Is making the piece display static while using the keyboard arrows intentional?
> 
> No. It's definitely a bug. Closing the dropdown should've detected the selection change.
> 
> -Dale

I'm afraid this answer didn't clarify the intended behavior for me.  The question I was trying to ask was whether the piece display should be changed in the `ON_CBN_SELCHANGE` handler or in the `ON_CBN_SELENDOK` handler.  The 'No' part of your answer sounds like updating the display `ON_CBN_SELCHANGE`, but the 'selection change' sounds like updating the display `ON_CBN_SELENDOK`.

**Comment by DLLarson** [comment]
Ok... I see more clearly what you are asking. I just tried the program after removing the `if` and it now updates changing the selection with the arrow keys. I don't really have any lags but my machine is pretty new.

>However, my preference is to make the piece display correspond to the focused name despite the slight delay. 

I think this is the correct approach because it tracks with what the dropdown does if you use the arrow keys when the dropdown isn't visible.

-Dale
