### ISSUE TITLE
file upgrade warning logic

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#59]
If I am reading the code correctly, both GM and GP only warn about upgrading a file if the file is older than version 2.90.  However, the file will still be upgraded for versions higher than that, but less than the current version.

Am I misunderstanding the code, or is there a reason the warning isn't displayed for version >= 2.9, or is this a bug (i.e., there should be a warning for any version less than the current one)?

**Comment by DLLarson** [comment]
It's a total bug. 

In fact I see a check for loading *newer* gamebox/game files right before the older file check and it looks proper. The older check should be the reverse of newer check. I must have missed all that during the MFC makeover. 

-Dale
