### ISSUE TITLE
CGamDoc::UpdateAllViews() logic looks strange

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#63]
This code looks strange to me:
```
void CGamDoc::UpdateAllViews(CView* pSender, LPARAM lHint, CObject* pHint)
{
    if (lHint & HINT_TILEGROUP || lHint & HINT_TILESETDELETED ||
        lHint & HINT_TILESETPROPCHANGE || lHint == HINT_ALWAYSUPDATE)
        m_palTile.UpdatePaletteContents();
    CDocument::UpdateAllViews(pSender, lHint, pHint);
}
```

For example, compare the above to the code in `CBrdEditView::OnUpdate()`.

I think `CGamDoc::UpdateAllViews()` should be:
```
void CGamDoc::UpdateAllViews(CView* pSender, LPARAM lHint, CObject* pHint)
{
    WORD wHint = LOWORD(lHint);
    if (
        ((wHint & HINT_TILEGROUP) && !(wHint & ~HINT_TILEGROUP)) ||
        wHint == HINT_TILESETDELETED ||
        wHint == HINT_TILESETPROPCHANGE ||
        wHint == HINT_ALWAYSUPDATE
        )
        m_palTile.UpdatePaletteContents();
    CDocument::UpdateAllViews(pSender, lHint, pHint);
}
```

If the original code is correct, could you explain how it works?

**Comment by DLLarson** [comment]
I don't see the problem. What `lHint & HINT_TILEGROUP || ...` says to me is if any of `HINT_TILECREATED`, `HINT_TILEMODIFIED` or `HINT_TILEDELETED` is set in the argument, the result will be non-zero which is true. Since they are mutually exclusive I simply numbered them sequentially starting at the first non-zero number.

-Dale

**Comment by wsu-cb** [comment]
But `HINT_BOARDPROPCHANGE & HINT_TILEGROUP` is also non-zero.  Is it intended that `HINT_BOARDPROPCHANGE` passes the `if` test?

**Comment by DLLarson** [comment]
Ahhhh...

I overlooked those lower bits. It's a bug although I may have known at the time (long long ago) that those hints wouldn't arrive in this particular case but it's definitely a hole in the logic.

-Dale
