### ISSUE TITLE
geomorphic unit board restriction?

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#74]
Can you explain why the hex grain direction must have an odd number of hexes?  I don't see an obvious problem with using a 4 x 4 unit board.

**Comment by DLLarson** [comment]
Hi,

The geomorphic board feature is patterned after maps that Avalon Hill created. If the hex grain direction was even the edges wouldn't line up when the boards are laid side-by-side:

https://boardgamegeek.com/image/20100/panzerblitz
https://en.wikipedia.org/wiki/Geomorphic_mapboard

Advanced Squad Leader used them as did a few more AH titles.

-Dale

**Comment by wsu-cb** [comment]
> Hi,
> 
> The geomorphic board feature is patterned after maps that Avalon Hill created. If the hex grain direction was even the edges wouldn't line up when the boards are laid side-by-side:
> 
> https://boardgamegeek.com/image/20100/panzerblitz https://en.wikipedia.org/wiki/Geomorphic_mapboard
> 
> Advanced Squad Leader used them as did a few more AH titles.
> 
> -Dale

I'm looking at the BGG image, and it looks to me like it has a width of 10 hexes, which is even.  Do you get a different count?

**Comment by DLLarson** [comment]
>I'm looking at the BGG image, and it looks to me like it has a width of 10 hexes, which is even. Do you get a different count?

Actually...after looking more closely it seems that it doesn't matter what the width is. They should always join. I can't remember why I said and had code enforce it.

I'll note that after all these years you're the first person to notice this. My guess is very few people must have used this feature.

This is a bug.

-Dale
