### ISSUE TITLE
fully hidden pieces on owned board

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#86]
Currently, a non-owner of a board can still see pieces on an owned board; the only limitation is the general restriction that a non-owner only sees the front of owned pieces.  However, for some games, it would be useful to completely hide pieces on an owned board.  For example, fully hidden movement, or an empire's economics record sheet.

I am thinking that it would be reasonable for a board with CPlayBoard::m_bNonOwnerAccess set to false to prevent showing pieces at all.

**Comment by wsu-cb** [comment]
Dale, does this proposal sound OK to you?

**Comment by DLLarson** [comment]
Hi Bill,

>I am thinking that it would be reasonable for a board with `CPlayBoard::m_bNonOwnerAccess` set to false 
>to prevent showing pieces at all.

I think it's reasonable but it is a change of behavior. In the help file these rules where laid out:

* IMPORTANT RULE: The OWNERship of a BOARD or a TRAY cannot be changed in a game. The OWNERship of pieces can change.

* IMPORTANT RULE: If a TRAY or BOARD is OWNed, then all the pieces residing in or on them are automatically set to be OWNed by that TRAY or BOARD's OWNER.

* IMPORTANT RULE: Pieces in non-OWNed TRAYs cannot be OWNed by anyone. Those pieces will have their OWNERship automatically cleared.

* IMPORTANT RULE: Pieces on non-OWNed BOARDs can either be OWNed or not OWNed. Non-OWNed BOARDs will probably be where most of the action takes place.

* Therefore, non-OWNERs of pieces will only see the FRONT tile image of them during play. OWNERs will see whatever image is on TOP.

The last item describes the current situation.

That said, what you're asking makes a lot of sense. I think it would be safer to add a board level option that said **_hide all owned items on the board_**. There may be the added complication of hiding any moves that occur on the owned boards during playback if that option is true.  This type of behavior is described in the help file:

>If a move affects a piece in a manner that should be hidden from view, the move is played back SILENTLY. The opponent is not be aware anything happened. The following operations performed on OWNed pieces will not be seen by your opponent:
>
>Flipping a piece over 
>Setting a piece's text 
>Locking or unlocking a Piece 

This behavior might need to be extended to all operations on a owned with the no-owned-visibility option set to true.

-Dale

**Comment by wsu-cb** [comment]
> I think it would be safer to add a board level option that said **_hide all owned items on the board_**. 

Actually, I want markers as well as pieces to be hidden, so I am thinking more in terms of **_Hide all items on this board from non-owners_**.

**Comment by wsu-cb** [comment]
> I wonder if we should show some sort of indicator over the map indicating it's contents are fully hidden to reduce player confusion.
> 

I don't like the move playback giving no display at all, so my current idea is to modify the move playback to show a tooltip reporting that hidden movement is being done, rather than actually show the move.  (The tooltip will always be at top-left so that its location doesn't give any clue to the user action.)  Sadly, this does seem to make the move playback noticeably more complicated, since I want the tooltip to only display once (per hidden board) per call to `CMoveList::DoMove()`.

Assuming the move playback alert, do you think the board also needs an indicator outside of playback time?  If so, I would instead suggest we prevent non-owners from opening "private" boards at all (show an error message box instead, both during move playback and when the user directly tries to open the board).

**Comment by DLLarson** [comment]
>Assuming the move playback alert, do you think the board also needs 
>an indicator outside of playback time? If so, I would instead suggest
>we prevent non-owners from opening "private" boards at all (show an 
>error message box instead, both during move playback and when the user 
>directly tries to open the board).

Riffing on the above...

How about, as you suggest, never allow the opening of a private board. Just provide a message box explaining the situation when a player tries to view it.

In the case of move playback, bring the project window forward and place a tooltip pointing at the private board item with a message saying that hidden activities are taking place on that board. Perform moves silently until encountering a move that has an effect outside the board such as dragging an item to/from the board to a tray or other board. 

Each time you'd normally bring the board forward for an unhidden action you would instead activate the project window and put a new tooltip (again explaining the situation) on the project window's private board entry as the target or originator of the move.

No matter what there will be some tricky stuff to deal with such as how to step back a move for instance.

-Dale

**Comment by wsu-cb** [comment]
> How about, as you suggest, never allow the opening of a private board. Just provide a message box explaining the situation when a player tries to view it.
> 
> In the case of move playback, bring the project window forward and place a tooltip pointing at the private board item with a message saying that hidden activities are taking place on that board. Perform moves silently until encountering a move that has an effect outside the board such as dragging an item to/from the board to a tray or other board.
> 
> Each time you'd normally bring the board forward for an unhidden action you would instead activate the project window and put a new tooltip (again explaining the situation) on the project window's private board entry as the target or originator of the move.
> 

This sounds pretty nice.  I will experiment with trying to implement this.


> No matter what there will be some tricky stuff to deal with such as how to step back a move for instance.
> 

Yes, I had thought of that annoyance.  I will have to see how messy things get.  I would think stepping forward is substantially more important, so as long as things work well going forward, I think I can live with some oddities in going backward, as long as they don't corrupt or crash the process.

**Comment by DLLarson** [comment]
>You are actively responding to this thread, but you haven't responded to the updated many-sided-piece PR. 

That totally dropped out of my view. Sorry about that. I'll make it a point to get that PR cleared this week.

If I don't respond on other need to happen PR's pop me a note if it seems to linger. I will at least give a response to when I can work on it. It takes a lot of digging--sometimes in the code history 

I do see three other requests for my thinking on several topics. I've been stacking them up to handle at once because they require I try to reconstruct my reasoning from really long ago which takes more effort then you might guess given my aging brain. Some things I may never remember the exact reasoning so I can only speculate on those.

-Dale
