### ISSUE TITLE
Why is CGamDoc's CRollState not serialized?

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#89]
`CGamDoc` has a `CRollState*` member, but it is explicitly commented as not being serialized.  It would be nice if it were serialized so that players of games like _Space Empires_ and _Empire of the Sun_ that always use 10-sided dice could avoid having to repeatedly set the dice face value.

So the question is why is `CGamDoc`'s `CRollState*` not serialized?

**Comment by DLLarson** [comment]
>So the question is why is CGamDoc's CRollState* not serialized?

Frankly I don't know why. 

If the player used a user supplied seed (such as the price of a stock on some day) the seed and its current propagated value should certainly be saved or the sequence won't be exactly reproducible if a player leaves the game and comes back to finish the move.

The comment suggests that I may have wanted to do it but had some doubt at that time. Or perhaps the information was stored somewhere else (I don't see it though.)

-Dale

**Comment by wsu-cb** [comment]
> Frankly I don't know why.
> 
> If the player used a user supplied seed (such as the price of a stock on some day) the seed and its current propagated value should certainly be saved or the sequence won't be exactly reproducible if a player leaves the game and comes back to finish the move.
> 
> The comment suggests that I may have wanted to do it but had some doubt at that time. Or perhaps the information was stored somewhere else (I don't see it though.)
> 
> -Dale

I have been working on a `.gbx` for d10-based _Space Empires_, and I have already changed the file format version, so I will experiment with saving the `CGamDoc` `CRollState*` and see if there is any obvious problem.

**Comment by DLLarson** [comment]
> I have been working on a `.gbx` for d10-based _Space Empires_, and I have already changed the file format version, so I will experiment with saving the `CGamDoc` `CRollState*` and see if there is any obvious problem.

I think that's a good idea.

**Comment by wsu-cb** [comment]
It looks like this didn't close automatically.
