### ISSUE TITLE
Handle Drag/Drop of selected objects into incompatible target views

### ISSUE THREAD

**Issue by DLLarson** [CyberBoardPBEM/cbwindows#96]
(Issues extracted from PR https://github.com/CyberBoardPBEM/cbwindows/pull/95)

Handle the following degenerative cases:

1. Selected objects could be so far apart that both can't be contained on the target view at the same time without changing their layout.
2. A single object could be so large it can't fit on the destination view.

**Comment by DLLarson** [comment]
The desired solution is to indicate the invalid drop locations using a new Cursor graphic that uniquely identifies this problem to the user.

-Dale

**Comment by DLLarson** [comment]
We need to reopen this issue.

I discovered that the ability to drag tiles onto playing board in `CBDesign.exe` is broken. No matter where I drag the tiles the "drop-not-allowed" cursor is displayed.

-Dale

**Comment by wsu-cb** [comment]
> I discovered that the ability to drag tiles from the Tile palette onto playing board in `CBDesign.exe` is broken. No matter where I drag the tiles the "drop-not-allowed" cursor is displayed.
> 
> -Dale

I can reproduce this.  I will investigate...
