### ISSUE TITLE
Fix flaw in Drag/Drop processing when dropping outside the view

### ISSUE THREAD

**Issue by DLLarson** [CyberBoardPBEM/cbwindows#97]
(Issue extracted from PR https://github.com/CyberBoardPBEM/cbwindows/pull/95)

Using this attached test file:

[big-and-small-boards.zip](https://github.com/CyberBoardPBEM/cbwindows/files/10033598/big-and-small-boards.zip)

Drag the markers from the big board to the small board, but do NOT actually drop the markers there.  Continue dragging until the mouse cursor is in the big board's `CSelectPieceView`.  The mouse cursor changes to show that dropping there is forbidden, but release the mouse anyway.  This seems to put CB in a strange state.  The `CSelectPieceView` shows the markers as selected, but the board does not (re)draw the markers with handles.  Also, the markers can still be dragged despite not showing handles, but if they are dragged, the tracking rectangles don't properly follow the mouse cursor.  If I switch the big board to its tiny view, I can see that dragging the markers shows the tracking rectangles for the markers far away from the mouse cursor.  So apparently drag-drop doesn't properly clean up a forbidden drop.

Another easier way to see this is:

1) Start with the original `.gsn`.
2) Select just the rightmost marker.
3) Drag the marker approximately two big-board cells to the right, so that the mouse is in the big board's tiny board window, and drop the marker in this forbidden window.
4) The result is that the marker stays displayed in its original location, and the `CSelectPieceView` shows the marker still selected, but the marker is displayed with no handles.  Also, if I drag the marker again, the tracking rectangle is in the wrong place.  Note that to see the tracking rectangle located incorrectly, the second drag has to be performed without unselecting and then reselecting the marker.

**Comment by DLLarson** [comment]
I don't think this has been resolved yet.

-Dale

**Comment by wsu-cb** [comment]
> I don't think this has been resolved yet.
> 
> -Dale

Can you give more detail on what isn't working here?  I just tried the master branch, and I'm not seeing a problem.

**Comment by DLLarson** [comment]
>Can you give more detail on what isn't working here? I just tried the master branch, and I'm not seeing a problem.

I just tried master as well. It's good. I'm reclosing.
