### ISSUE TITLE
Fix XOR Artifacts Visible When Dragging Selected Object Along View Edge.

### ISSUE THREAD

**Issue by DLLarson** [CyberBoardPBEM/cbwindows#98]
(Issue extracted from PR https://github.com/CyberBoardPBEM/cbwindows/pull/95)

When selected objects are dragged along the edge of a board view I see this:

![image](https://user-images.githubusercontent.com/175455/201529296-013ad2fd-c5ca-401b-8a2a-48d84b8ffb2e.png)

But it doesn't always happen. It's almost like a race condition. I was running both the 64bit and 32bit debug versions of this PR to test.

Here's a procedure to reproduce this behavior:

1) Start with the original `.gsn`.
2) Select just the rightmost marker.
3) Drag the marker to the right, but don't actually move the cursor into the tiny board view.  Instead move the mouse cursor just far enough to the right to have the cursor just slightly to the left of the scroll bar.  I see the tracking rectangle start blinking.  Now start moving the mouse cursor up and down.  The blinking tracking rectangle will leave artifacts, which actually sort of make sense, because the XOR drawing logic could easily miss its tracking rectangle erase if the mouse moves at a bad time.

Use the following test file:

[big-and-small-boards.zip](https://github.com/CyberBoardPBEM/cbwindows/files/10033676/big-and-small-boards.zip)

**Comment by DLLarson** [comment]
This one wasn't resolved so I've reopened it.
-Dale

**Comment by wsu-cb** [comment]
> This one wasn't resolved so I've reopened it. -Dale

Can you give more detail on what isn't working?  I don't see any problem with this when I run the master branch?

**Comment by DLLarson** [comment]
This is working as well. I must have been testing the wrong build. Re-Closing...

-Dale
